name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        # Maps port 6379 on service container to the host
        - 6379:6379

    env:
      RACK_ENV: test
      GEMFILE_RUBY_VERSION: 3.0.3

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.70.1
        with:
          ruby-version: '3.0.1'
        

      - name: Bundle
        run: |
          bundle

      - name: Run tests
        env:
          SCHEMAS_PATH: spec/fixtures/schemas
          REDIS_URL: redis://localhost:6379
        run: |
          # run tests
          bundle exec rspec
